# This GitHub Action Workflow will handle a **COMPLETE** Regular Release.
# Handling all aspects possible of the release itself.
name: Automated Regular Release (Full)

on:
  workflow_dispatch:

env:
  # Variables needed
  nextPulsarVersion: "null" # Set by 'findNextPulsarVersion' script
  releasePrLink: "null" # Set via CLI in 'Create GitHub Pull Request'
  binaryDir: "pulsar-bins" # The directory that should contain finalized binaries
  #releaseType: "minor" # The type of bump we are doing during a release. "minor"
                       # the default for Pulsar, as we don't bump major ever
  releaseType: "patch"

jobs:
  full-regular-release:
    runs-on: ubuntu-latest
    steps:
    #### Setup
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: latest

    - name: Checkout this Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Install this repositories dependencies
      run: npm install

    - name: Setup Git User
      run: |
        git --version
        git config user.name "Pulsar-Edit Bot"
        git config user.email "<no-reply@users-github.com>"
        git config --global credential.helper store
        echo "https://x-access-token:${{ secrets.AUTH_TOKEN_GITHUB }}@github.com" > ~/.git-credentials
        git status

    #### Tag New Release
    - name: Clone the pulsar-edit/pulsar repository
      uses: actions/checkout@v4
      with:
        repository: pulsar-edit/pulsar
        path: pulsar

    - name: Find new Version
      run: |
        node ./findNextPulsarVersion \
          --packageLocation "pulsar/package.json" \
          --envVarOutput "nextPulsarVersion" \
          --bumpType ${{ env.releaseType }}
        echo "DEBUG: nextPulsarVersion: ${{ env.nextPulsarVersion }}"

    - name: Create new branch under new version
      run: git switch -c v${{ env.nextPulsarVersion }}-release origin/master
      working-directory: pulsar

    - name: Bump Pulsar Version
      run: npm version ${{ env.releaseType }}
      working-directory: pulsar
      
    - name: Remove 'package.json' version build identifier
      run: node ./removeBuildIdFromVersion --packageLocation "pulsar/package.json"

    - name: Commit changes
      run: git commit -m "Update Version"
      working-directory: pulsar

    - name: Tag changes
      run: git tag v${{ env.nextPulsarVersion }}
      working-directory: pulsar

    - name: Push Branch to Remote
      run: git push -u origin v${{ env.nextPulsarVersion }}-release
      working-directory: pulsar

    - name: Create GitHub Pull Request
      run: |
        gh pr create \
          --title "v${{ env.nextPulsarVersion }} Release" \
          --body "Automated Regular Release" >> $env:releasePrLink
        echo "DEBUG: releasePrLink: ${{ env.releasePrLink }}"
      working-directory: pulsar

    - name: Push tag to remote
      run: git push origin v${{ env.nextPulsarVersion }}
      working-directory: pulsar

    #### Manage Bins
    - name: Download bins as they become available
      run: |
        node ./downloadBinsWhenPossible \
          --saveLoc ${{ env.binaryDir }} \
          --releasePrLink ${{ env.releasePrLink }} \
          --githubAuthToken ${{ secrets.AUTH_TOKEN_GITHUB }} \
          --tag v${{ env.nextPulsarVersion }}

    - name: Move all bins into the top level directory
      # Since the binaries are downloaded into sub folders based on category
      # we first need to move them all up into the current directory
      run: mv */* .
      working-directory: ${{ env.binaryDir }}

    - name: Delete all empty subdirectories (Which all should be)
      run: find . -type d -empty -delete
      working-directory: ${{ env.binaryDir }}

    - name: Generate SHASUMS file
      run: sha256sum * | tee SHA256SUMS.txt
      working-directory: ${{ env.binaryDir }}

    #### Publish Bins
    - name: Create Release & Upload all Bins
      run: |
        node ./createReleaseAndUploadBins \
          --binLoc ${{ env.binaryDir }} \
          --version v${{ env.nextPulsarVersion }} \
          --githubAuthToken ${{ secrets.AUTH_TOKEN_GITHUB }}

    #### Cleanup
    - name: Add back 'package.json' build identifier
      run: |
        node ./addBuildIdToVersion \
          --packageLocation "pulsar/package.json"

    - name: Commit these changes
      run: git commit -m "Add back build identifier"
      working-directory: pulsar

    - name: Push Branch to Remote
      run: git push -u origin v${{ env.nextPulsarVersion }}-release
      working-directory: pulsar

    # TODO Do we want to auto-close the PR created?
